#! /usr/bin/env/ruby
# frozen_string_literal: true

require 'simplecov'

SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter
])

SimpleCov.minimum_coverage 90
SimpleCov.start

require 'minitest'

old_dir = Dir.pwd
Dir.chdir './test'

files = Dir.glob('**/*_test.rb').map { |f| File.expand_path f }
Dir.chdir old_dir

files.each { |f| require f }

success = Minitest.run ['-vp']

exit 1 unless success
